### ISSUE TITLE
projects at pgrouting.org

### ISSUE THREAD

**Issue by cvvergara** [pgRouting/admin#3]
Questions
- [x] Who gets that mail?
- [x] Can an automatic forward be made so we all receive the mail?

**Comment by dkastl** [comment]
I get the mail. It's a very simple forwarding from the domain registrar service.
I didn't want to setup something like Google Apps for this. There is a very low number of emails sent to this email address (<20 per year). Usually they are from users, who are not able to ask their questions on the appropriate channels.

I don't want to send the emails directly to the mailing list, because senders may not agree with making them public.

So I currently don't have a simple solution, but I also think, that the number of emails sent to this address, and the value of the content is worth the effort ;-)

**Comment by cvvergara** [comment]
Can they be forwarded to me & steve?

**Comment by dkastl** [comment]
I need to check that simple forwarder, if it accepts a list of email addresses. Otherwise I need to setup some group mail address.

**Comment by dkastl** [comment]
Currently forwarded to @cvvergara and @dkastl . Ask @dkastl to be added to the list of recipients (currently managed in Mailgun). For larger group of people we may want to use a mailing list.
